version: "3"

networks:
  masters:
    external: true

services:
  ms-2:
    image: ms-2
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "81:8080"
    networks:
      - masters